name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install LLVM
      run: |
        sudo apt-get purge --auto-remove llvm* clang* lld* lldb* -y
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo apt-add-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-17 main"
        sudo apt-get install clang-17 lld-17 -y
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-17 400
        sudo update-alternatives --install /usr/bin/ld.lld ld.lld /usr/bin/ld.lld-17 400

    - name: Run tests without LTO
      run: cargo test

    - name: Run tests with LTO
      run: RUSTFLAGS="-Clinker-plugin-lto -Clinker=clang -Clink-arg=-fuse-ld=lld" cargo test --features lto